# Generated by Django 4.0.4 on 2022-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('High', 'High'), ('Medium', 'Medium')], max_length=32, null=True),
        ),
    ]
