# Generated by Django 4.0.4 on 2022-12-19 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.date(2022, 12, 19)),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('Medium', 'Medium'), ('High', 'High'), ('low', 'low')], max_length=32, null=True),
        ),
    ]
