# Generated by Django 4.0.4 on 2022-12-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.IntegerField(blank=True, choices=[(36, '(36) Thirty six weeks'), (1, '(1) One week'), (3, '(3) Three weeks'), (48, '(48) Fourty eight weeks'), (12, '(12) Twelve weeks'), (16, '(16) Sixteen weeks'), (44, '(44) Fourty four weeks'), (28, '(28) Tweny eight weeks'), (32, '(32) Thirty two weeks'), (24, '(24) Twenty four weeks'), (2, '(2) Two weeks'), (20, '(20) Twenty weeks'), (8, '(8) Eight weeks'), (40, '(40) Fourty weeks'), (4, '(4) Four weeks')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('low', 'low')], max_length=32, null=True),
        ),
    ]
