# Generated by Django 4.0.4 on 2022-12-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_deadline_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('low', 'low'), ('Medium', 'Medium')], max_length=32, null=True),
        ),
    ]
