# Generated by Django 4.0.4 on 2022-12-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_remove_task_deadline_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('low', 'low')], max_length=32, null=True),
        ),
    ]
