# Generated by Django 4.0.4 on 2022-12-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
