# Generated by Django 4.0.4 on 2022-12-19 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0017_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('completionDate', models.DateField(blank=True, null=True)),
                ('deadline', models.IntegerField(blank=True, choices=[(1, '(1) One week'), (8, '(8) Eight weeks'), (28, '(28) Tweny eight weeks'), (16, '(16) Sixteen weeks'), (3, '(3) Three weeks'), (12, '(12) Twelve weeks'), (4, '(4) Four weeks'), (24, '(24) Twenty four weeks'), (40, '(40) Fourty weeks'), (36, '(36) Thirty six weeks'), (48, '(48) Fourty eight weeks'), (20, '(20) Twenty weeks'), (44, '(44) Fourty four weeks'), (32, '(32) Thirty two weeks'), (2, '(2) Two weeks')], null=True)),
                ('priority', models.CharField(blank=True, choices=[('Medium', 'Medium'), ('low', 'low'), ('High', 'High')], max_length=32, null=True)),
                ('categories', models.ManyToManyField(blank=True, null=True, to='task.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
