# Generated by Django 4.1.4 on 2022-12-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='categories',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.IntegerField(blank=True, choices=[(8, '(8) Eight weeks'), (44, '(44) Fourty four weeks'), (48, '(48) Fourty eight weeks'), (32, '(32) Thirty two weeks'), (40, '(40) Fourty weeks'), (1, '(1) One week'), (2, '(2) Two weeks'), (36, '(36) Thirty six weeks'), (12, '(12) Twelve weeks'), (4, '(4) Four weeks'), (20, '(20) Twenty weeks'), (16, '(16) Sixteen weeks'), (3, '(3) Three weeks'), (24, '(24) Twenty four weeks'), (28, '(28) Tweny eight weeks')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('low', 'low'), ('Medium', 'Medium')], max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.status'),
        ),
    ]
