# Generated by Django 4.1.4 on 2022-12-21 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0019_status_remove_task_categories_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.IntegerField(blank=True, choices=[(12, '(12) Twelve weeks'), (32, '(32) Thirty two weeks'), (20, '(20) Twenty weeks'), (28, '(28) Tweny eight weeks'), (3, '(3) Three weeks'), (48, '(48) Fourty eight weeks'), (40, '(40) Fourty weeks'), (2, '(2) Two weeks'), (44, '(44) Fourty four weeks'), (1, '(1) One week'), (4, '(4) Four weeks'), (16, '(16) Sixteen weeks'), (36, '(36) Thirty six weeks'), (24, '(24) Twenty four weeks'), (8, '(8) Eight weeks')], null=True),
        ),
    ]
