# Generated by Django 4.0.4 on 2022-12-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_alter_task_deadline_board_status_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=34),
        ),
    ]
