# Generated by Django 4.0.4 on 2022-12-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_alter_board_title_alter_status_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completionDate',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
